[WIP]Kev Adding Docstrings
anthonyjclark/gaitpt pull request #1
Opened 2021-10-15 00:34 UTC by Kayala47

Not quite done yet, but just figured out how to make the PR (I think!). I think the rest of the functions needing documentation are a little more unclear for me.

2021-10-15 16:00 UTC, anthonyjclark requested changes

2021-10-15 16:00 UTC, anthonyjclark commented on gait_pt.py
Use the `black` code formatter prior to submitting a PR. This will make it so that all style choices are consistent between us.

2021-10-15 16:00 UTC, anthonyjclark commented on gait_pt.py
> +    def motion_step(self, hip_x: float, foot_delta: float = 8 / (32/3)) -> Tuple[float, float]:
Thanks for adding the parameter! Instead of adding a default value here, just pass in the `8 / (32/3)` where this method is called below.

2021-10-15 16:00 UTC, anthonyjclark commented on gait_pt.py
> +            previous version of code.
Great! Please update the docstring to remove your mention of the todo.

2021-10-15 16:00 UTC, anthonyjclark commented on gait_pt.py
> +        #TODO: should this return 0,0 if not swinging?
You are correct.

2021-10-15 16:00 UTC, anthonyjclark commented on gait_pt.py
> +        TODO: I don't really understand this section..
Fair enough! This is some weird matplotlib stuff. Now that you've seen it, we should go over it together in person.

2021-10-21 23:23 UTC, Kayala47 commented on gait_pt.py
> +        leg_poses = [leg.motion_step(self.hip_x, 8 / (32 / 3)) for leg in self.legs]
don't define foot delta here, do it at the topmost level.

2021-11-01 17:58 UTC, anthonyjclark approved these changes

2021-11-01 17:59 UTC, merged